version: '3.8'

services:
  web:
    image: php:7.4-apache
    container_name: php-apache
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - dns
    networks:
      - app-network
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=dbname

  dns:
    image: internetsystemsconsortium/bind9:9.16
    volumes:
      - ./bind:/etc/bind
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ=Asia/Tehran
    networks:
      - app-network
      
  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8090:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
